Repository simelo/cgogen, pull requests merged in 2020-02, with the labels that each got.

#20 [cmd] Fixes #19 Added support change prefix functions and errors
  CHANGELOG.md
  src/cmd/cgogen.go
Labels: good first issue, stdev, wip

#22 [cmd] Fixes #21 Added new parameter to define mainPackage
  src/cmd/cgogen.go
Labels: stdev, wip

#26 Fixes #25 Normalized and format code
  src/cmd/cgogen.go
Labels: bug, stdev, wip

#28 [cgogen] Fixes #27 Adding support to configure the inplace through configuration file
  src/cmd/cgogen.go
Labels: bug, stdev, wip

#24 Fixes #23 Added support autogenerate Slice
  src/cmd/cgogen.go
Labels: bug, stedev, wip

#32 fixes #31 GitHub templates v2
  .github/ISSUE_TEMPLATE/blank.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/issue_template.md
Labels: ci

#30 Fixes #29 Added support `customType` in cfg
  src/cmd/cgogen.go
Labels: bug, stdev, wip
